export const divisionsData = [
  {
    name: "BPI",
    fullName: "Badan Pengurus Inti",
    image: "BPI.png",
    colorClass: "emerald",
    description: "Badan Pengurus Inti (BPI) bertanggung jawab mengoordinasi operasional harian organisasi dan memastikan setiap program kerja berjalan dengan lancar, efektif, dan tepat sasaran sesuai visi organisasi.",
  },
  {
    name: "PSDM",
    fullName: "Pengembangan Sumber Daya Manusia",
    image: "PSDM.png",
    colorClass: "rose",
    description: "Pengembangan Sumber Daya Manusia (PSDM) bertanggung jawab menciptakan ekosistem yang suportif dan berkualitas bagi seluruh mahasiswa Program Studi Informatika. Divisi ini memastikan organisasi tidak hanya berjalan dengan baik, tetapi juga berkembang, sehat, dan mampu beradaptasi dari generasi ke generasi.",
  },
  {
    name: "Humas",
    fullName: "Hubungan Masyarakat",
    image: "HUMAS.png",
    colorClass: "teal",
    description: "Hubungan Masyarakat (Humas) bertanggung jawab membangun dan mempertahankan hubungan yang solid dengan stakeholder internal dan eksternal organisasi untuk meningkatkan citra dan kolaborasi organisasi.",
  },
  {
    name: "Litbang",
    fullName: "Penelitian dan Pengembangan",
    image: "LITBANG.png",
    colorClass: "blue",
    description: "Penelitian dan Pengembangan (Litbang) melakukan penelitian terhadap upaya optimalisasi dan pengembangan kualitas sumber daya mahasiswa dalam bidang akademik yang bersifat inovatif, kolaboratif, dan berbasis penalaran.",
  },
  {
    name: "Mediatek",
    fullName: "Media dan Teknologi",
    image: "MEDIATEK.png",
    colorClass: "purple",
    description: "Media dan Teknologi (Mediatek) mengelola semua aspek media komunikasi organisasi dengan mengolah ide menjadi konten berkualitas, merawat platform digital agar selalu terkini, serta memastikan semua informasi mudah diakses dan tersaji dengan baik.",
  },
  {
    name: "KWU",
    fullName: "Kewirausahaan",
    image: "KWU.png",
    colorClass: "cyan",
    description: "Kewirausahaan (KWU) membina dan mendorong jiwa wirausaha anggota melalui program pengembangan bisnis, riset pasar, pengembangan produk, serta strategi pemasaran yang inovatif dan berkelanjutan.",
  },
];

export const colorMap = {
  emerald: {
    cardDark: "border-emerald-500/20 hover:border-emerald-500/50",
    cardLight: "border border-emerald-200 hover:border-emerald-400 hover:bg-emerald-50",
    bgDark: "bg-gradient-to-br from-emerald-500/5 to-transparent",
    bgLight: "bg-gradient-to-br from-emerald-100/30 to-transparent",
    titleDark: "text-emerald-300 group-hover:text-emerald-400",
    titleLight: "text-emerald-700 group-hover:text-emerald-800",
  },
  teal: {
    cardDark: "border-teal-500/20 hover:border-teal-500/50",
    cardLight: "border border-teal-200 hover:border-teal-400 hover:bg-teal-50",
    bgDark: "bg-gradient-to-br from-teal-500/5 to-transparent",
    bgLight: "bg-gradient-to-br from-teal-100/30 to-transparent",
    titleDark: "text-teal-300 group-hover:text-teal-400",
    titleLight: "text-teal-700 group-hover:text-teal-800",
  },
  cyan: {
    cardDark: "border-cyan-500/20 hover:border-cyan-500/50",
    cardLight: "border border-cyan-200 hover:border-cyan-400 hover:bg-cyan-50",
    bgDark: "bg-gradient-to-br from-cyan-500/5 to-transparent",
    bgLight: "bg-gradient-to-br from-cyan-100/30 to-transparent",
    titleDark: "text-cyan-300 group-hover:text-cyan-400",
    titleLight: "text-cyan-700 group-hover:text-cyan-800",
  },
  blue: {
    cardDark: "border-blue-500/20 hover:border-blue-500/50",
    cardLight: "border border-blue-200 hover:border-blue-400 hover:bg-blue-50",
    bgDark: "bg-gradient-to-br from-blue-500/5 to-transparent",
    bgLight: "bg-gradient-to-br from-blue-100/30 to-transparent",
    titleDark: "text-blue-300 group-hover:text-blue-400",
    titleLight: "text-blue-700 group-hover:text-blue-800",
  },
  purple: {
    cardDark: "border-purple-500/20 hover:border-purple-500/50",
    cardLight: "border border-purple-200 hover:border-purple-400 hover:bg-purple-50",
    bgDark: "bg-gradient-to-br from-purple-500/5 to-transparent",
    bgLight: "bg-gradient-to-br from-purple-100/30 to-transparent",
    titleDark: "text-purple-300 group-hover:text-purple-400",
    titleLight: "text-purple-700 group-hover:text-purple-800",
  },
  rose: {
    cardDark: "border-rose-500/20 hover:border-rose-500/50",
    cardLight: "border border-rose-200 hover:border-rose-400 hover:bg-rose-50",
    bgDark: "bg-gradient-to-br from-rose-500/5 to-transparent",
    bgLight: "bg-gradient-to-br from-rose-100/30 to-transparent",
    titleDark: "text-rose-300 group-hover:text-rose-400",
    titleLight: "text-rose-700 group-hover:text-rose-800",
  },
};
